### PR TITLE
Improved versions of KMeans in Pharo 3 and 4 - should now come in jus…

### PR DESCRIPTION
**Pull request by roelWuyts**
…t before Python (keeping my fingers crossed ;-) )

### CODE REVIEW

**Comment by andreaferretti** [comment]
Sorry if I answer this late, but it is not clear to me what this PR changes. I only see an object to start the benchmark. Why should this change the performance?

**Comment by roelWuyts** [comment]
Dear Andrea,

I slightly rewrote the various classes (keeping the same algorithms as instructed), and added some class-level methods and comments for clarity – I think something went wrong in the fileout because I know see that it indeed is strange. I will fileout and commit a new version.

Sorry for that !

Kind regards,

Roel

**Comment by roelWuyts** [comment]
Dear Andrea,

I just had a look and am completely confused. I haven’t used git in a while, but maybe I am doing something terribly wrong here ☹

What I don’t understand is the following: when I look at the ‘raw’ file [1] I see the class definitions I updated, as well as for example a new cluster:around: method I changed. But when I look at only the changes these new definitions are not marked as being new ?!

I really don’t understand this – the Pharo4.0 directory for example is new, hence the single file in it is also completely new, but even there only the beginning of the file is marked by git as being new (the rest of the file, with the updated cluster:around: method is there but not marked as changed even though the complete file is new).

Do you have any idea what the problem could be or what I have to do ?

[1] https://github.com/roelWuyts/kmeans/commit/13d9964c3ddd8d2e575650002ef755da5ca37893

**Comment by andreaferretti** [comment]
I am confused as well. Anyway, I will just take the raw files and import them :-)

It has been a while since I had Pharo installed, and I see that latest Pharo is version 5. Do you think the Pharo4 examples will run there? Or is better to try the in Pharo4?

**Comment by roelWuyts** [comment]
I think the Pharo4 will run fine in Pharo5, if not tell me and I’ll update them.

They should run faster in 5, but when I tested it was with a beta version so I didn’t want to submit them just yet.

I didn’t do Smalltalk in a while but couldn’t resist. I’m a colleague from Wilfried, so when he told me about the benchmarks I just had to give it a try ;-)

Kind regards,

Roel

**Pull request merged**
