### PR TITLE
Optimize groupBy using sofs

### PR DESCRIPTION
**Pull request by bjorng**
On my computer, this optimization made it run 10 times faster.

### CODE REVIEW

**Comment by andreaferretti** [comment]
Just to be sure - I received the Erlang example, so I am not able to judge. The examples in other languages all use a `groupBy` operation, which in turn is usually implemented with a hashmap. Is this approach in Erlang equivalent?

**Comment by bjorng** [comment]
sofs does not use a hash map. It works by sorting the
list and then goes through the sorted list and groups
the values.

The rules says "idiomatic code", so I wrote idiomatic
code.

On Tue, Feb 24, 2015 at 10:55 AM, andreaferretti notifications@github.com
wrote:

> Just to be sure - I received the Erlang example, so I am not able to
> judge. The examples in other languages all use a groupBy operation, which
> in turn is usually implemented with a hashmap. Is this approach in Erlang
> equivalent?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreaferretti/kmeans/pull/12#issuecomment-75727892.

## 

Björn Gustavsson, Erlang/OTP, Ericsson AB

**Comment by andreaferretti** [comment]
Unfortunately, this makes hard to compare the results with other languages. Would it be possible to provide a hashmap-based implementation?

**Comment by jlouis** [comment]
In general, no. Hashmaps in the traditional sense can't be implemented in a functional language because of data persistence. You can fake hashmaps pretty well through HAMT structures, but you won't get the same speed as a system which is able to do destructive updates. Once you begin looking at idiomatic Haskell or OCaml, chances are this will bite you as well.

**Comment by andreaferretti** [comment]
Well, HashMaps certainly do no need to be mutable. Scala has immutable, persistent hashmaps, and I think both OCaml and Haskell have them (but I am not sure).

**Comment by jlouis** [comment]
Both OCaml and Haskell have hashmap implementations, but you run into the trouble of what idiomatic means.

**Comment by andreaferretti** [comment]
I settled accepting the other pull request which follows more closely what is done in other languages

**Pull request closed without merging**
